import { Coordinate } from '../types';
import { getBitBoardValue } from '../bitboard';

import _pieceData from './pieces.json'; // https://www.gottfriedville.net/blokus/set.png
import _orientationData from './piece-orientations.json';
import _orientationBitboardData from './piece-orientations-bitboard.json';
import _orientationBitboardHaloData from './piece-orientations-bitboard-halo.json';
import _rrData from './piece-rr.json';
import _cornersData from './piece-corners.json';
import _shortBoundingBoxData from './piece-short-bounding-box.json';
import _cornerAttachersData from './piece-corner-attachers.json';
import { Board } from '../board';
import { coordinateInBounds } from './movegen-utils';

export type PieceData = Coordinate[];

// index into the "pieceData"
export type PieceType = number;
export type Player = 0 | 1;

// 16 bit integer bitfield
export type PackedMove = number;

const MOVE_ORIENTATION_MASK = 0x7;
const MOVE_Y_MASK = 0x78;
const MOVE_X_MASK = 0x780;
const MOVE_TYPE_MASK = 0xf800;
const MOVE_PLAYER_BIT = 0x10000;

export const getMoveOrientation = (packedMove: PackedMove): number => {
    return packedMove & MOVE_ORIENTATION_MASK;
};

export const getMoveX = (packedMove: PackedMove): number => {
    return (packedMove & MOVE_X_MASK) >> 7;
};

export const getMoveY = (packedMove: PackedMove): number => {
    return (packedMove & MOVE_Y_MASK) >> 3;
};

export const getMoveLocation = (packedMove: PackedMove): Coordinate => {
    return { x: getMoveX(packedMove), y: getMoveY(packedMove) };
};

export const getMovePieceType = (packedMove: PackedMove): number => {
    return (packedMove & MOVE_TYPE_MASK) >> 11;
};

export const getMovePlayer = (packedMove: PackedMove): Player => {
    return ((packedMove & MOVE_PLAYER_BIT) >> 16) as Player;
};

// Sentinel value, invalid for an actual move since there cannot be a move with piece type 31.
export const NULL_MOVE = 0xf800;

export interface PlacedPiece {
    pieceType: PieceType;
    location: Coordinate;
    player: Player;
    orientation: number;
}

export const serializePlacedPiece = (placedPiece: PlacedPiece): PackedMove => {
    return (
        placedPiece.orientation |
        (placedPiece.location.y << 3) |
        (placedPiece.location.x << 7) |
        (placedPiece.pieceType << 11) |
        (placedPiece.player << 16)
    );
};

/**
 * A move is either a placement of a piece or a transfer of the turn to the other player.
 */
export type Move = PackedMove;

export interface Permutation {
    rotation: number;
    reflection: boolean;
    data: PieceData;
}

export const pieceData: Readonly<PieceData[]> = _pieceData;
export const orientationData: Readonly<PieceData[][]> = _orientationData;
export const orientationBitBoarddata: Readonly<number[][][]> = _orientationBitboardData;
export const orientationBitBoardHaloData: Readonly<number[][][]> = _orientationBitboardHaloData;
export const RRData: Readonly<number[][]> = _rrData;
export const cornersData: Readonly<PieceData[][]> = _cornersData;
export const cornerAttachersData: Readonly<PieceData[][]> = _cornerAttachersData;
export const shortBoundingBoxData: Readonly<[number, number][][]> = _shortBoundingBoxData as [
    number,
    number,
][][];

export const getOrientationData = (pieceType: PieceType, orientation: number) => {
    return orientationData[pieceType][orientation];
};

export const PIECE_SIZES: readonly number[] = pieceData.map((p) => p.length);
export const PIECE_WEIGHTS: readonly number[] = PIECE_SIZES.map((s) => 1 << Math.min(s, 8));

export type StartPosition = 'middle' | 'corner' | 'middle-blokee';

/**
 * Given a pseudo-legal move generated by intermediate operations in functions like getLegalMovesFrom, verifies that it is legal
 * Which means that none of it's tiles are adjacent to any of the players, nor intersecting any other placed piece
 * @param pseudoLegalMove The pseudolegal move to test
 * @param state The context within which it's legality is checked
 * @returns Whether the move is legal
 */
export const isMoveLegal = (pseudoLegalMove: Move, state: Board): boolean => {
    // We assume if a null move was generated, it was legal
    // We don't check if there is actually a reason for a null move - like if there are zero valid moves
    if (pseudoLegalMove === NULL_MOVE) {
        return true;
    }

    const player = (pseudoLegalMove & MOVE_PLAYER_BIT) >> 16;
    const type = (pseudoLegalMove & MOVE_TYPE_MASK) >> 11;
    const ori = pseudoLegalMove & MOVE_ORIENTATION_MASK;
    const x = (pseudoLegalMove & MOVE_X_MASK) >> 7;
    const y = (pseudoLegalMove & MOVE_Y_MASK) >> 3;

    const remaining = player === 0 ? state.state.playerARemaining : state.state.playerBRemaining;
    if ((remaining & (1 << type)) === 0) {
        return false;
    }

    const myBitBoard = player === 0 ? state.state.playerABitBoard : state.state.playerBBitBoard;
    const opponentBitBoard =
        player === 0 ? state.state.playerBBitBoard : state.state.playerABitBoard;

    const shortBoundingBox = shortBoundingBoxData[type][ori];
    const brx = x + shortBoundingBox[0];
    const bry = y + shortBoundingBox[1];
    if (x < 0 || y < 0 || x > 13 || y > 13 || brx < 0 || bry < 0 || brx > 13 || bry > 13) {
        return false;
    }

    const pieceBitboard = orientationBitBoarddata[type][ori];
    for (let bitboardY = 0; bitboardY < pieceBitboard.length; bitboardY++) {
        if ((pieceBitboard[bitboardY] << x) & opponentBitBoard[bitboardY + y]) {
            return false;
        }
    }

    const haloData = orientationBitBoardHaloData[type][ori];
    const myLen = myBitBoard.length;
    for (let bitboardY = 0; bitboardY < pieceBitboard.length + 2; bitboardY++) {
        const row = y + bitboardY - 1;
        if (row < 0 || row >= myLen) {
            continue;
        }
        if ((haloData[bitboardY] << x) & (myBitBoard[row] << 1)) {
            return false;
        }
    }

    return true;
};

/** True if the placement overlaps `bitboard` (no halo / remaining checks). */
export const moveOverlaps = (move: Move, bitboard: number[]): boolean => {
    if (move === NULL_MOVE) {
        return false;
    }
    const type = (move & MOVE_TYPE_MASK) >> 11;
    const ori = move & MOVE_ORIENTATION_MASK;
    const x = (move & MOVE_X_MASK) >> 7;
    const y = (move & MOVE_Y_MASK) >> 3;
    const pieceBitboard = orientationBitBoarddata[type][ori];
    for (let bitboardY = 0; bitboardY < pieceBitboard.length; bitboardY++) {
        if ((pieceBitboard[bitboardY] << x) & bitboard[bitboardY + y]) {
            return true;
        }
    }
    return false;
};

/**
 * Get the set of moves that originate from the `from` coordinate, usually a corner to another placed piece, of a given piece type.
 * @param from The coordinate through which the piece must go through
 * @param piece The type of piece
 * @param state Current board state
 * @returns An array of legal moves
 */
export const getLegalMovesFrom = (from: Coordinate, piece: PieceType, state: Board): Move[] => {
    const moves: Move[] = [];
    const player = state.state.toMove;
    const fromX = from.x;
    const fromY = from.y;
    const orientations = orientationData[piece];

    for (let i = 0; i < orientations.length; i++) {
        const orientationCorners = cornersData[piece][i];
        for (let c = 0; c < orientationCorners.length; c++) {
            const corner = orientationCorners[c];
            const mx = fromX - corner.x;
            const my = fromY - corner.y;
            if (mx < 0 || my < 0 || mx > 13 || my > 13) {
                continue;
            }
            const move = i | (my << 3) | (mx << 7) | (piece << 11) | (player << 16);
            if (isMoveLegal(move, state)) {
                moves.push(move);
            }
        }
    }

    return moves;
};

/**
 * Blokee's middle start position is unique in that the move must be entirely contained within your quadrant
 * @param move
 */
const isMoveBlokeeLegal = (move: PlacedPiece, pieceTiles: PieceData) => {
    return pieceTiles.every((relCoord) => {
        const absolute = { x: relCoord.x + move.location.x, y: relCoord.y + move.location.y };
        if (move.player === 0) {
            // bottom left
            return absolute.x <= 6 && absolute.y > 6;
        } else {
            // top right
            return absolute.x > 6 && absolute.y <= 6;
        }
    });
};

/**
 * Generates the set of valid moves for the first turn of the game, which is different.
 * The placed piece must simply cover the starting position, which can be either in the corner or near the middle.
 * @param board The current state
 * @returns
 */
const START_SQUARES: Record<StartPosition, [Coordinate, Coordinate]> = {
    middle: [
        { x: 4, y: 4 },
        { x: 9, y: 9 },
    ],
    corner: [
        { x: 0, y: 0 },
        { x: 13, y: 13 },
    ],
    'middle-blokee': [
        { x: 6, y: 7 },
        { x: 7, y: 6 },
    ],
};

const firstMoveCandidates = (startPosName: StartPosition, player: Player): Move[] => {
    const startPos = START_SQUARES[startPosName][player];
    const moves: Move[] = [];
    for (let piece = 0; piece < 21; piece++) {
        for (let i = 0; i < orientationData[piece].length; i++) {
            const pieceTiles = orientationData[piece][i];
            for (let t = 0; t < pieceTiles.length; t++) {
                const tile = pieceTiles[t];
                const mx = startPos.x - tile.x;
                const my = startPos.y - tile.y;
                if (mx < 0 || my < 0 || mx > 13 || my > 13) {
                    continue;
                }
                const placedPiece: PlacedPiece = {
                    location: { x: mx, y: my },
                    player,
                    pieceType: piece,
                    orientation: i,
                };
                if (
                    startPosName === 'middle-blokee' &&
                    !isMoveBlokeeLegal(placedPiece, pieceTiles)
                ) {
                    continue;
                }
                moves.push(serializePlacedPiece(placedPiece));
            }
        }
    }
    return moves;
};

const FIRST_MOVE_CANDIDATES: Record<StartPosition, [Move[], Move[]]> = {
    middle: [firstMoveCandidates('middle', 0), firstMoveCandidates('middle', 1)],
    corner: [firstMoveCandidates('corner', 0), firstMoveCandidates('corner', 1)],
    'middle-blokee': [
        firstMoveCandidates('middle-blokee', 0),
        firstMoveCandidates('middle-blokee', 1),
    ],
};

const EMPTY_FIRST_LEGAL: Partial<Record<string, Move[]>> = {};

const generateFirstMove = (board: Board): Move[] => {
    const candidates = FIRST_MOVE_CANDIDATES[board.state.startPosName][board.state.toMove];
    if (board.state.pieces.length === 0) {
        const key = `${board.state.startPosName}:${board.state.toMove}`;
        const cached = EMPTY_FIRST_LEGAL[key];
        if (cached !== undefined) {
            return cached.slice();
        }
        const legal: Move[] = [];
        for (let i = 0; i < candidates.length; i++) {
            if (isMoveLegal(candidates[i], board)) {
                legal.push(candidates[i]);
            }
        }
        EMPTY_FIRST_LEGAL[key] = legal;
        return legal.slice();
    }
    const legal: Move[] = [];
    for (let i = 0; i < candidates.length; i++) {
        if (isMoveLegal(candidates[i], board)) {
            legal.push(candidates[i]);
        }
    }
    return legal;
};

/**
 * Get all the legal moves from the current player to move
 * @param board The current board state
 * @returns
 */
export const getAllLegalMoves = (board: Board): Move[] => {
    if (board.gameOver()) {
        return [];
    }

    const myRemaining =
        board.state.toMove === 0 ? board.state.playerARemaining : board.state.playerBRemaining;
    if (myRemaining === 0x1fffff) {
        return generateFirstMove(board);
    }

    const cache =
        board.state.toMove === 0 ? board.state.playerACornerMoves : board.state.playerBCornerMoves;
    const uniqueMoves = uniqueMovesFromCache(cache);

    if (uniqueMoves.length === 0) {
        uniqueMoves.push(NULL_MOVE);
    }

    return uniqueMoves;
};

const MOVE_SEEN = new Uint32Array(1 << 17);
let MOVE_SEEN_EPOCH = 1;

const uniqueMovesFromCache = (cache: Map<number, Move[]>): Move[] => {
    MOVE_SEEN_EPOCH++;
    if (MOVE_SEEN_EPOCH === 0xffffffff) {
        MOVE_SEEN.fill(0);
        MOVE_SEEN_EPOCH = 1;
    }
    const uniqueMoves: Move[] = [];
    for (const moves of cache.values()) {
        for (let i = 0; i < moves.length; i++) {
            const move = moves[i];
            if (MOVE_SEEN[move] !== MOVE_SEEN_EPOCH) {
                MOVE_SEEN[move] = MOVE_SEEN_EPOCH;
                uniqueMoves.push(move);
            }
        }
    }
    return uniqueMoves;
};

export const pieceSize = (move: Move): number => {
    if (move === NULL_MOVE) {
        return 1;
    }
    return PIECE_SIZES[getMovePieceType(move)];
};

export const sizeWeight = (move: Move): number => {
    if (move === NULL_MOVE) {
        return 2;
    }
    return PIECE_WEIGHTS[getMovePieceType(move)];
};

export const pickSizeWeightedFromList = (plays: Move[]): Move => {
    if (plays.length === 1) {
        return plays[0];
    }
    let total = 0;
    for (const move of plays) {
        total += sizeWeight(move);
    }
    let r = Math.floor(Math.random() * total);
    for (const move of plays) {
        const w = sizeWeight(move);
        if (r < w) {
            return move;
        }
        r -= w;
    }
    return plays[plays.length - 1];
};

/**
 * Size-weighted sample for rollouts. Walks the corner cache and skips
 * dedup (duplicates just add weight), packing only the chosen move.
 */
export const pickSizeWeightedMove = (board: Board): Move => {
    if (board.gameOver()) {
        return NULL_MOVE;
    }

    const myRemaining =
        board.state.toMove === 0 ? board.state.playerARemaining : board.state.playerBRemaining;
    if (myRemaining === 0x1fffff) {
        return pickSizeWeightedFromList(getAllLegalMoves(board));
    }

    const cache =
        board.state.toMove === 0 ? board.state.playerACornerMoves : board.state.playerBCornerMoves;

    let total = 0;
    for (const moves of cache.values()) {
        for (let i = 0; i < moves.length; i++) {
            total += PIECE_WEIGHTS[getMovePieceType(moves[i])];
        }
    }
    if (total === 0) {
        return NULL_MOVE;
    }

    let r = (Math.random() * total) | 0;
    for (const moves of cache.values()) {
        for (let i = 0; i < moves.length; i++) {
            const move = moves[i];
            const w = PIECE_WEIGHTS[getMovePieceType(move)];
            if (r < w) {
                return move;
            }
            r -= w;
        }
    }
    return NULL_MOVE;
};
